//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheAuctioneerEntities : DbContext
    {
        public TheAuctioneerEntities()
            : base("name=TheAuctioneerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auction> Auction { get; set; }
        public virtual DbSet<AuctionStatus> AuctionStatus { get; set; }
        public virtual DbSet<Bid> Bid { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<TokenOrder> TokenOrder { get; set; }
        public virtual DbSet<TokenOrderStatus> TokenOrderStatus { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
